### ISSUE TITLE
Plugins don't seem to load in postcss-loader 1.0.0

### ISSUE THREAD

**Issue by dkrutsko** [postcss/postcss-loader#118]
Using Webpack **2.1.0-beta.25**, postcss-loader **1.0.0** and the example [**here**](https://github.com/postcss/postcss-loader#webpack-2x-config), I'm trying to load `postcss-cssnext` and `postcss-position-alt` but none of them load.

Looking into the code [here](https://github.com/postcss/postcss-loader/blob/master/index.js#L47), I don't think `loaderUtils.parseQuery` works to parse functions. Furthermore, even if you made the `plugins` key an array, it still wouldn't correctly parse certain plugins.

At this point I'm thinking that this is just a limitation of Webpack and I'm not sure how it could get fixed.

**Comment by ai** [comment]
I have tested ` loaderUtils.parseQuery` and it works fine. Could you provide your config? Also have you tested PostCSS common config, that we recommend to use?

**Comment by dkrutsko** [comment]
Yes I have tested the common config. Here's the relevant part of my config:

```js
{
  module: {
    rules: [
      {
        test: /\.scss$/i,
        use:
        [
          {
            loader: "style"
          },
          {
            loader: "css"
          },
          {
            loader : "postcss",
            options: {
              plugins: function()
              {
                return [
                  require ("postcss-cssnext")
                  ({
                    // Config
                  }),

                  require ("postcss-position-alt")
                ];
              }
            }
          }
        ]
      }
    ]
  }
}
```

In postcss-loader, ```loaderUtils.parseQuery``` returns an empty object.

**Comment by ai** [comment]
And what is your results with common PostCSS config?

**Comment by ai** [comment]
Could you create a test project? I will look at it today evening

**Comment by dkrutsko** [comment]
Absolutely! Attached is a zip containing 4 files. Unzip them inside a folder and run the following:

```bash
npm install
npm install -g webpack@~2.1.0-beta
webpack
```

This will compile style.css into bundle.css. The expected output of bundle.css should be:

```css
body
{
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    color: rgb(200, 200, 200);
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
}
```
[test.zip](https://github.com/postcss/postcss-loader/files/536693/test.zip)

**Comment by ai** [comment]
I found a problem ;). You will be surprised.

Problem is with your JS coding style ;). You insert a `\n` between `return` and plugins list:

```js
					{
						loader: "postcss",
						options:
						{
							plugins: function()
							{
								return
								[
									require ("postcss-cssnext"),
									require ("postcss-position-alt")
								];
							}
						}
					}
```

So JS think that you returns nothing ;). I remove this new line and everything works on me.

I got his `bundle.css`:

```css
body
{
	display: -webkit-box;
	display: -ms-flexbox;
	display: flex;
	color: rgb(200, 200, 200);
	position: absolute;
	left: 0;
	bottom: 0;
	right: 0;
	top: 0;
}
```
