### ISSUE TITLE
Unexpected character issues when using `url` inside pcss

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-loader#160]
I'm getting the following errors when loading assets in pcss with url :
```css
@font-face {
  font-family: "sofachrome";
  src: url(../fonts/sofachrome.regular.ttf) format("truetype");
}
body {
  background: url("../img/globe.png");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  color: #cafaea;
  background-color: #000000 !important;
  background-attachment: fixed;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

```
ERROR in ./img/globe.png
Module parse failed: /Users/nikos/WebstormProjects/quantumjs/img/globe.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
ERROR in ./fonts/sofachrome.regular.ttf
Module parse failed: /Users/nikos/WebstormProjects/quantumjs/fonts/sofachrome.regular.ttf Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
```
```js
var path = require("path");
var webpack = require("webpack");
var WebpackBuildNotifierPlugin = require("webpack-build-notifier");


const PATHS = {
  src: path.join(__dirname, './src'),
  build: path.join(__dirname, './build')
};

module.exports = {

  entry: {
    "app": PATHS.src + '/index.ts'
  },
  output: {
    path: PATHS.build,
    filename: '[name].js'
  },
  devtool: "source-map",
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'ts-loader'
      },
      {
        test: /\.pcss$/,
        loaders: [
          'style-loader',
          'css-loader?importLoaders=1',
          'postcss-loader'
        ]
      }
    ]
  },
  resolve: {
    // you can now require('file') instead of require('file.js')
    extensions: ['.ts', '.js','.pcss']
  },
  plugins: [
    new WebpackBuildNotifierPlugin({
      title: "My Project Webpack Build"
    })
  ]
};
```
