### ISSUE TITLE
OTS parsing error: invalid version tag with @font-face, doesn't occur in css-loader

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-loader#167]
Try this in a pcss file:

```css

@font-face {
  font-family: 'Droid Sans Mono';
  src: url('https://fonts.googleapis.com/css?family=Droid+Sans+Mono'); /* IE9 Compat Modes */
}
```

loader:
```js
      {
        test: /\.p?css$/,
        loaders: [
          'style-loader',
          'css-loader?importLoaders=1,url=false',
          'postcss-loader'
        ]
      }

```

browser error:

```
Failed to decode downloaded font: https://fonts.googleapis.com/css?family=Droid+Sans+Mono
index.html?_ijt=f53nmid9tc5kd6n3dr8lesk2j5:1 OTS parsing error: invalid version tag
```
