### ISSUE TITLE
Chunk.entry was removed. Use hasRuntime()

### ISSUE THREAD

**Issue by willin** [postcss/postcss-loader#170]
```js
        use: ExtractTextPlugin.extract([
          'style-loader',
          'css-loader?importLoaders=1',
          'postcss-loader'   // if i add this line
        ])
```

error shows:

```
/Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/Chunk.js:59
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/Chunk.js:59:9)
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/willin/Documents/js.cool/hosts.js/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/Users/willin/Documents/js.cool/hosts.js/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/Compilation.js:558:8)
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/Compiler.js:474:16
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/Compilation.js:472:11)
    at processModuleDependencies.err (/Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

dep:

```js
 "devDependencies": {
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "postcss-loader": "^1.2.2",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.1"
  }
```

**Comment by michael-ciniawsky** [comment]
@willin Could you try the following please ? `style-loader` should in any case not be part of the extract pipeline and only used as fallback in case the extraction fails.

webpack: `v2.2.1`
extract-text-plugin: `v2.0.0-rc.3`

```js
use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [ 
              { loader: 'css-loader', options: { importLoaders: 1 } },
              'postcss-loader'
          ]
       })
```

**Comment by michael-ciniawsky** [comment]
`"extract-text-webpack-plugin": "^1.0.1" => "extract-text-plugin": "2.0.0-rc.3"`

**Comment by willin** [comment]
oh yes. thx

**Comment by willin** [comment]
```css
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(MaterialIcons-Regular.woff2) format('woff2'),
       url(MaterialIcons-Regular.woff) format('woff'),
       url(MaterialIcons-Regular.ttf) format('truetype');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;  /* Preferred icon size */
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;

  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;

  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;

  /* Support for IE. */
  font-feature-settings: 'liga';
}
```


```
ERROR in ./assets/fonts/iconfont/material-icons.css
Module build failed: Error
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/webpack/lib/NormalModule.js:141:35
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/willin/Documents/js.cool/hosts.js/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/willin/Documents/js.cool/hosts.js/node_modules/postcss-loader/index.js:141:13
 @ ./src/app/main.js 1:457-495
 @ multi webpack-hot-middleware/client?noInfo=true&reload=true ./src/app/main.js
```
