### ISSUE TITLE
[2.0.5] Output CSS Reversed/Jumbled

### ISSUE THREAD

**Issue by skipjack** [postcss/postcss-loader#210]
I'm seeing a weird issue with the output from this loader. I can't share the actual code/output but this is essentially what's happening:

__prior to loading__

``` css
.some-class {
  display: flex;
  flex-direction: column;
  color: black;

  &--mod {
    color: white;
  }
}
```

__after loading__

``` css
.some-class--mod {
  color: white;
}
.some-class {
  display: flex;
  flex-direction: column;
  color: black;
}
```

It's not all an exact reverse, but most of it is and the rest just seems randomly jumbled. Obviously this screws up the cascade (i.e. when `some-class` and `some-class--mod` are applied to the same element, the `color` is `black` instead of `white`). 

Here are the plugins I'm using _postcss-import_, _postcss-modular-scale_, _postcss-cssnext_, and _postcss-nested_.
