### ISSUE TITLE
[2.1.0] Add `url()` handling (`postcss-icss-url`)

### ISSUE THREAD

**Issue by michael-ciniawsky** [postcss/postcss-loader#228]
### `postcss-icss-url`

https://github.com/TrySound/postcss-icss-url

### `postcss-loader`

```
// TODO
```

**Comment by clydin** [comment]
With `dependency` message support inlining, I believe, is handled quite nicely.
For copying to the output, however, this is really only half the puzzle.  To fully support webpack plugins that modify/optimize assets as well as virtual filesystems support (for webpack-dev-server, etc.), additional support is required by both `postcss-loader` and `postcss-url` to provide a mechanism to inject the asset into the webpack compilation instance.

An additional `asset` message could be handled by `postcss-loader` which would provide the name/size/content of the asset.  On the `postcss-url` side, a new action type could be created (`inject` for instance) which would construct and send the message.

**Comment by michael-ciniawsky** [comment]
@clydin Something in that direction yes, but if possible we should try to avoid adding build tool specifics to postcss plugins (`postcss-url`), but a generic `replace, inject` option (unrelated, but compatible with webpack (`postcss-loader`)) would be ok I guess 😛. Also help wanted on this🥇

**Comment by clydin** [comment]
Another option that keeps everything incredibly generic would be to create a helper function `addAsset` on the `postcss-loader` instance.  Then provide documentation with a sample custom `postcss-url` action function that leverages `addDependency`, `addAsset`, and adjusts the URL.
The large downside is the complexity of the function that everyone would have to reuse.  The URL would potentially need to be rebased, the file would need to be resolved, the `add*` calls, etc.

**Comment by evilebottnawi** [comment]
@michael-ciniawsky https://github.com/TrySound/postcss-icss-url

**Comment by michael-ciniawsky** [comment]
Yep 😛 , is it for `url()` only ?

**Comment by TrySound** [comment]
@michael-ciniawsky Yep. Only url in properties.

**Comment by michael-ciniawsky** [comment]
@TrySound 👍 && `postcss-modules-parser` => `postcss-icss` (ICSS 2) for @import =>`:import :export` with `media query`?

**Comment by TrySound** [comment]
For `@import` I guess we need another plugin converted.

**Comment by evilebottnawi** [comment]
@TrySound After implement `postcss-icss-import` we can have a full compatibility with `icss2` and in theory use `new-css-loader`, right?

**Comment by TrySound** [comment]
Yep. I'm gonna do this in next few days.

**Comment by evilebottnawi** [comment]
@TrySound awesome! Let me know when you do it. I will test this on a couple of big projects

**Comment by TrySound** [comment]
Did you already run new loader?

**Comment by evilebottnawi** [comment]
@TrySound yep, all works fine excluding `@import` and `url` :smile:

**Comment by TrySound** [comment]
Did you check url plugin?

**Comment by evilebottnawi** [comment]
@TrySound Not yet, I'll try in the near future

**Comment by michael-ciniawsky** [comment]
@TrySound The plugin (`postcss-icss-url`) is awesome 👍 

```js
const plugins = [
  require('postcss-modules-values')(),
  require('postcss-modules-local-by-default')(),
  require('postcss-modules-extract-imports')(),
  // require('postcss-modules-resolve-imports')(),
  require('postcss-modules-scope')(),
  // postcss-modules-parser => postcss-icss
  require('postcss-modules-parser')(), // <= | I wonder about the plugin order here, but
  require('postcss-icss-url')() // <======== | postcss-modules-parser after postcss-icss-url   
                                            // throws unhandled exception, maybe my fault ¯\_(ツ)_/¯
]
```

```css
:import('img.png'){
  __url_0: default
}

:import('/img.png'){
  __url_1: default
}

:import('./img.png'){
  __url_2: default
}

:import('../img.png'){
  __url_3: default
}

/*  postcss-icss-import */
@import '/style.css';
@import './style.css';
@import '../style.css';

@import '@org/package';
@import 'package';

@import 'https://domain.com/asssts/style.css';

._Users_Cini_Github_PostCSS_test_src_index__url {
  background-url: url(__url_0)
}

._Users_Cini_Github_PostCSS_test_src_index__url2 {
  background-url: url(__url_1)
}

._Users_Cini_Github_PostCSS_test_src_index__url3 {
  background-url: url('//img.png')
}

._Users_Cini_Github_PostCSS_test_src_index__url4 {
  background-url: url(__url_2);
}

._Users_Cini_Github_PostCSS_test_src_index__url5 {
  background-url: url(__url_3);
}

._Users_Cini_Github_PostCSS_test_src_index__url7 {
  background-url: ('https://domain.com/assets/img.png');
}
```

```
// result.root.tokens (postcss-modules-parser [postcss-icss])
// Could/Should we chnge that to result.messages ? (result.messages.?)
{
  "url": "_Users_Cini_Github_PostCSS_test_src_index__url",
  "url2": "_Users_Cini_Github_PostCSS_test_src_index__url2",
  "url3": "_Users_Cini_Github_PostCSS_test_src_index__url3",
  "url4": "_Users_Cini_Github_PostCSS_test_src_index__url4",
  "url5": "_Users_Cini_Github_PostCSS_test_src_index__url5",
  "url7": "_Users_Cini_Github_PostCSS_test_src_index__url7"
}
```

- `postcss-icss-import` will work the same ?  

```
// result.root.tokens || result.messages.?
{
  "import": "...__import"
  "import2": "...__import2"
}
``` 

:warning: 😛  General question of mine in terms of plugin order, is it safe to we push/append the ICSS Plugins (automatically) via `postcss-loader` or will this break, so explicit user setup is better ?  😛 ⚠️ 

@evilebottnawi How did you build the `new-loader` branch to test it in a webpack setup, manually run the build and copy & paste ? 😭
