### ISSUE TITLE
Nested Syntax CSS cannot be recognized 

### ISSUE THREAD

**Issue by martinyeh** [postcss/postcss-loader#243]
I already added in my webpack.config.js
```
  loaders: [{
      test: /\.css$/,   // *.css but not *.theme.css
      loader: `${STYLE_LOADER}?insertAt=top!${CSS_LOADER}!postcss-loader`,
      exclude: /node_modules/,
    }],
```
Here is part of my css file:
```
.app-header {	
  position: relative;
	padding-top: 33px;

  &.app-title{ 
  font: 300 48px/1 var(--font-family-base-oscine);  
  color: #FFFFFF;
  cursor: default;
  position: relative;
  z-index: 3;
  max-width: 730px;
  word-break: break-all;
  }
}
```
and part of my html file:
```
const Header =({app}) => {
	if(!app){
		return <div>The app title</div>;
	}
	return(	 
		<div className="app-header">
      		<div><h1 className="app-title">{app.title}</h1></div>
			<div className="app-name">{app.name}</div>
		</div>
	);
};
```
I found that the css style didn't apply to app-title. Why is that ?

**Comment by michael-ciniawsky** [comment]
From the fomer issue like a commented in a example you basically use 2 nesting plugins atm, but that shouldn't be the main issue here 😛 

```css
.app {
  display: flex;

  &__foo {
    color: red;
  }

  &__bar {
    color: blue;
  }
}
```


```css
.app { display: flex; }
.app__foo { color: red; }
.app__bar { color: blue; }
```

Remove the `app` prefixes from the nested selectors, that's what nesting is actually for  😛 :D
