### ISSUE TITLE
postcss-cssnext only handles nested selectors one level deep when used with postcss-loader

### ISSUE THREAD

**Issue by JadedDragoon** [postcss/postcss-loader#265]
What it says on the tin. When using postcss and postcss-cssnext with gulp-postcss everything works as expected. My .cssnext file (example below) is transpiled correctly.

When the same file and postcss config is run through postcss-loader, either with "css-loader & style-loader" or "file-loader & style-loader/url" the resulting css has only the first level of nested rules "flattened" and the rest are simply copied. This also affects nested media queries.

The only postcss plugins I am using is postcss-import and postcss-cssnext.

```css
@import './root.cssinc';

/*** Main Menu ***/
#menus-app {
    font-size: 1.6rem;

    & .rnav-menu,
    & .lnav-menu {
        position: relative;

        & > a {
            font-size: 1.4em;
        }

        & li a { /* overrides for html5bp */
            text-align: left;
            margin-bottom: 0;
            padding: 0;
            font-weight: normal;

            @media only screen and (width >= 480px) {
                width: auto;
                margin: 0;
                float: none;
            }
        }

        & .app-item {
            /* shape */
            border: 2px solid var(--fgCol);
            display: block;
            padding: 1em;

            /* content style */
            background-color: var(--maskCol);
        }

        & div {
            /* override html5bp */
            width: auto;
            margin: auto;
            float: none;
        }

        & .nav-item a {
            /* shape */
            border: 2px solid var(--fgCol);
            display: block;
            padding: 0.875em 0.5em;

            /* content style */
            font-weight: bold;
            background-color: var(--maskCol);
        }

        & ul {
            /* sidebar fundamentals */
            display: block;
            z-index: 1000;

            /* shape */
            border: 2px solid var(--fgCol);

            /* content style */
            background-color: var(--fgCol);

            @media only screen and (width < 768px) {
                /* sidebar fundamentals */
                position: fixed;
                overflow-y: scroll;
                top: 0;
                bottom: 0;

                /* animation */
                transition: 0.5s ease;
                transition-property: left, right;

                /* shape */
                width: 12.5em;
            }

            @media only screen and (width >= 768px) {
                /* dropdown fundamentals */
                position: absolute;
                overflow-y: auto;
                top: 96px;
                right: 0;
                max-height: 50vh;

                /* animation */
                transition: 0.3s ease-in-out;
                transition-property: visibility, opacity;
                visibility: hidden;
                opacity: 0;

                /* shape */
                width: 15.625em;
                border-color: var(--fgCol);
                box-shadow: 2px 2px 7px 0 var(--shadowCol);
            }
        }

        & .nav-close {
            @media only screen and (width >= 768px) { display: none; }
        }
    }

    & .lnav-menu .nav-cur-cat span {
        /* shape */
        display: block;
        border: 2px solid var(--fgCol);
        padding: 0.25em;

        /* content style */
        background-color: var(--fgCol);
        text-align: center;
        font-size: 1.2em;
        font-weight: bold;
    }

    & .lnav-menu ul {
        @media only screen and (width < 768px) {
            /* animation */
            right: -13.125em;

            /* shape */
            box-shadow: -2px 0 7px 0 var(--shadowCol);
        }
    }

    & .rnav-menu ul {
        @media only screen and (width < 768px) {
            /* animation */
            left: -13.125em;

            /* shape */
            box-shadow: 2px 0 7px 0 var(--shadowCol);
        }
    }

    & .rnav-animate ul,
    & .lnav-animate ul {
        @media only screen and (width < 768px) {
            /* animation */
            transform: translate(0, 0);
        }

        @media only screen and (width >= 768px) {
            visibility: visible;
            opacity: 1;
        }
    }

    & .lnav-animate ul {
        @media only screen and (width < 768px) {
            /* animation */
            right: 0;
        }
    }

    & .rnav-animate ul {
        @media only screen and (width < 768px) {
            /* animation */
            left: 0;
        }
    }
}
```
