### ISSUE TITLE
`-webkit-box-orient` has been removed?

### ISSUE THREAD

**Issue by aleen42** [postcss/postcss-loader#341]
I have recently update dependencies of my project and use Webpack 3 to build, and found a strange thing when using `postcss-loader` with `autoprefixer`. If set with `-webkit-box-orient: vertical;`, and I got the output file without this property. Please check whether it is a bug of `autoprefixer`?

### `Reproduction [Code]`
---

```css
.test {
    /** ... */
    display: -webkit-box;
    -webkit-box-orient: vertical;
}
```

Got:

```css
.test {
    /** ... */
    display: -webkit-box;
}
```

### `Environment`
---

|OS|node|npm|PostCSS|
|:-:|:--:|:-:|:------:|
|Windows 10|v7.10.1|5.4.2|2.1.1|
