### ISSUE TITLE
Not all border widths set to 0 loads as `border-width: 0`

### ISSUE THREAD

**Issue by eivisand** [postcss/postcss-loader#342]
When two or more `border-{edge}-width: 0` and `border-{different-edge}: borderstyle` are defined, the output after postcss is `border-width: 0; border-{different-edge}: borderstyle;`, meaning it sets all border-widths to 0 even if only two or more are set.

### `Reproduction [Code]`
---
originalStyle.css:
```css
.onlyBorderBottom {
  border-top-width: 0;
  border-right-width: 0;
  border-bottom: 1px solid #222;
  border-left-width: 0;
}
.onlyBorderBottom--topWidthNotSet {
  border-right-width: 0;
  border-bottom: 1px solid #222;
  border-left-width: 0;
}
.onlyBorderBottom--rightWidthZero {
  border-right-width: 0;
  border-bottom: 1px solid #222;
}
```

outputStyle.css:
```css
.onlyBorderBottom{
  border-bottom: 1px solid #222;
  border-width: 0;
}
.onlyBorderBottom--topWidthNotSet{
  border-bottom: 1px solid #222;
  border-width: 0;
}
.onlyBorderBottom--rightWidthZero{
  border-right-width: 0;
  border-bottom: 1px solid #222;
}
```

.postcssrc.js:
```
module.exports = {
  plugins: [
    require('cssnano')({
      autoprefixer: { add: true },
      discardComments: { removeAll: true },
      discardDuplicates: true,
      discardEmpty: true,
      discardOverridden: true,
      discardUnused: true,
      reduceIdents: false,
      reduceInitial: false,
      reduceTransforms: false,
      zindex: false
    })
  ]
};
```
webpack.config.js:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ]
      }
    ]
  }
}
```

### `Environment`
---

|OS|node|npm|PostCSS|
|:-:|:--:|:-:|:------:|
|OS: windows10|node: 8.9.4|npm: 5.6.0|PostCSS: 2.1.0|
