### ISSUE TITLE
-ms-transform is not added

### ISSUE THREAD

**Issue by ahmedelgabri** [postcss/postcss-loader#37]
Here the code

```css
.Demo {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

Running this script I get the right output
```js
var fs = require('fs')
var path = require('path')
var postcss = require('postcss')
var css = fs.readFileSync(path.join(__dirname, 'public/src/css/index.css'))

postcss([
  require('postcss-import')({
    path: [ path.join(__dirname, 'public/src/css'), path.join(__dirname, 'modal/css') ]
  }),
  require('postcss-custom-properties'),
  require('postcss-nested'),
  require('autoprefixer')({
    browsers: ['last 2 versions', 'ie >= 9']
  })
]).process(css).then(function (result) {
  result.warnings().forEach(function (warn) {
    console.warn(warn.toString())
  })
  console.log(result.css)
})

```

```css
.Demo {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}
```

But with these Webpack settings

```js
var path = require('path')
var webpack = require('webpack')
var ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = {
  entry: path.join(__dirname, 'public/src/js/index.js'),
  output: {
    filename: path.join(__dirname, 'public/build/js/build.js')
  },
  resolve: {
    extensions: ['', '.js'],
    alias: {
      modal: path.join(__dirname, './modal/js/index.js')
    }
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel'
      },
      {
        test: /\.ejs$/,
        loader: 'ejs-loader'
      },
      {
        test: /\.css/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')
      }
    ]
  },
  plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({ compress: { warnings: false } }),
    new ExtractTextPlugin(path.join(__dirname, 'public/build/css/style.css'), { allChunks: true }),
    new webpack.ProvidePlugin({ _: 'lodash' })
  ],
  postcss: function (webpack) {
    return [
      require('postcss-import')({
        path: [ './public/src/css', './modal/css' ],
        addDependencyTo: webpack
      }),
      require('postcss-custom-properties'),
      require('postcss-nested'),
      require('autoprefixer')({
        browsers: ['last 2 versions', 'ie >= 9'],
        remove: false // even this doesn't work
      })
    ]
  }
}
```

I get this 
```css
.Demo {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%,-50%);
  transform: translate(-50%,-50%)
}
```

**Comment by ai** [comment]
Very strange, that in webpack outut `transform` has no indent like in first one. Do you sure, that there is no other CSS tools?

Also you can put a `console.log` inside a `postcss-loader` to get real input/output to the loader.

**Comment by ahmedelgabri** [comment]
@ai I copied and pasted the Webpack output from the css file that's why there is no indentation.

I added a `console.log()` [here](https://github.com/postcss/postcss-loader/blob/master/index.js#L51) and surprisingly the output is right

```css

.Demo {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}
```
and no I don't have any other CSS tools running in this project.
