### ISSUE TITLE
postcss-loader doesn’t process CSS Modules composition target

### ISSUE THREAD

**Issue by iamakulov** [postcss/postcss-loader#40]
[CSS Modules](https://github.com/css-modules/css-modules) have [a class composition feature](https://github.com/css-modules/css-modules#composition) which acts similarly to LESS’ `:extend()` rule. It is enabled by the `composes` property. The problem is that the class referenced by this property is not processed by `postcss-loader`.

Example:

```css
/* a.css */
.a {
  display: flex;
}

/* b.css */
.b {
  composes: a from "./a.css";
  user-select: none;
}
```

```js
/* Webpack config */
module.exports = {
  module: {
    loaders: [
      {
        test: /\.css$/,
        loaders: ['style-loader', 'css-loader?modules&localIdentName=[name]--[local]--[hash:base64:5]', 'postcss-loader']
      }
    ]
  },
  postcss: function () {
    return [autoprefixer({ browsers: ['last 2 versions'] })];
  }
};
```

With `autoprefixer` added, the code is compiled to the following:

```css
/* b.css */
.b {
  display: flex;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

As you see, the `user-select` property is processed and prefixed, whereas `display: flex` is not.
