### ISSUE TITLE
Add documentation to readme on how to use with sass-loader

### ISSUE THREAD

**Issue by ajsharp** [postcss/postcss-loader#42]

**Comment by MoOx** [comment]
Just use sass-loader before (so after in the loader definition). This should not need any specific doc.

**Comment by ai** [comment]
Sorry `postcss-loader` can’t have a docs for every webpack loader.

I can change my mind if this issue will be popular.

**Comment by ajsharp** [comment]
@MoOx Yea, I tried that autoprefixer, and it doesn't seem to work. Here's my config:

```js
var webpack = require('webpack');
var path = require('path');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var autoprefixer = require('autoprefixer');
var precss = require('precss');

module.exports = {
  context: __dirname,

  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js'
  },

  entry: {
    app: './js/app.js'
  },

  module: {
    loaders: [
      {
        test: /\.(scss|sass)$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'postcss-loader', 'sass-loader')}
    ]
  },

  postcss: function() {
    return [autoprefixer, precss];
  },

  sassLoader: {
    includePaths: [path.join(__dirname, 'scss')]
  },

  plugins: [
    new ExtractTextPlugin('styles.css')
  ]
}
```

Here's the sass file:
```scss
.banner {
  background-color: green;
  font-size: 48px;
  text-align: center;
  color: white;
  border-radius: 4px;
  box-shadow: black 1px 1px 1px;
  transform: rotate(7deg);
}
```

And the output file:

```css
.banner {
  background-color: green;
  font-size: 48px;
  text-align: center;
  color: white;
  border-radius: 4px;
  box-shadow: black 1px 1px 1px;
  transform: rotate(7deg);
}
```

@ai Using this loader with sass or less is an extremely common use-case -- no one in practice is writing plain-vanilla CSS. I think it would be very useful to have a concrete example of how to use these tools together.
