### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by f0rmat1k** [postcss/postcss-loader#52]
Sry for such issue, but it rly doesn't working, i've tried everything.
```js
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var autoprefixer = require('autoprefixer');

module.exports = {
	context: __dirname + "/blocks",
	entry: "./page.js",
	output: {
		path: __dirname + "/public",
		filename: "bundle.js"
	},
	module: {
		loaders: [
			{
				test: /\.css$/,
				loader: ExtractTextPlugin.extract('style-loader', 'css-loader', 'postcss-loader')
			}

		]
	},
	plugins: [
		new ExtractTextPlugin("bundle.css")
	],
	postcss: function () {
		return [ autoprefixer({ browsers: ['last 5 versions'] }) ];
	}
};
```

```css
body
{
    transform: translateZ(0);
    user-select: none;
    display: flex;
    border-radius: 10px;
}
```
becomes in bundle.css as
```css
body
{
    transform: translateZ(0);
    user-select: none;
    display: flex;
    border-radius: 10px;
}
```

What am I doing wrong?
