### ISSUE TITLE
Trouble with Babel 6 `export default` and postcss-js

### ISSUE THREAD

**Issue by montemishkin** [postcss/postcss-loader#55]
Not sure if this is an issue with my setup, postcss-loader, or postcss-js but I figured I would start here.

I've made a repo that reproduces the problem [here](https://github.com/montemishkin/postcss-loader-issue) (see its README for how to reproduce).

Essentially the issue is that this

```js
// styles.js
const x = 10


export default {
    '.something': {
        color: 'red',
        padding: x,
    }
}
```

is getting transformed into this

```css
default {
    .something {
        color: red;
        padding: 10px
    }
}
```

rather than this

```css
.something {
    color: red;
    padding: 10px
}
```

Let me know if I can provide any further helpful info.  Thanks!
