### ISSUE TITLE
Importing global styles while avoiding duplicates.

### ISSUE THREAD

**Issue by unindented** [postcss/postcss-loader#63]
Say our codebase has one CSS file per component:

```
components/
├── foo
│   ├── index.js
│   └── index.css
└── bar
    ├── index.js
    └── index.css
```

And we have a bunch of variables and utility classes that we want to make available to all CSS files, so that they can use the variables and `@extend` from the utility classes:

```css
:root {
  --color-white: #fff;
  --color-black: #000;
  ...
}

.u-clearfix:before,
.u-clearfix:after {
  content: " ";
  display: table;
}
.u-clearfix:after {
  clear: both;
}
```

Currently we prefix all CSS files with `@import "globals.css";` through a loader:

```js
{
  test: /\.css$/,
  exclude: /node_modules\//,
  loader: ExtractTextPlugin.extract('style', [
    'css?-url', // disable url handling for now
    'postcss',
    'wrap?css'
  ])
},

postcss: function (webpack) {
  return [
    postcssImport({addDependencyTo: webpack}),
    postcssVars({preserve: false}),
    postcssExtend(),
    autoprefixer()
  ];
},

wrap: {
  css: {
    before: '@import "globals.css";'
  }
}
```

This makes the variables and classes available, but causes a ton of duplication, as each file has a copy of the `globals.css` file.

How would you tackle that problem?
