### ISSUE TITLE
Autoprefixer and precss do not appear to be loading

### ISSUE THREAD

**Issue by hankthewhale** [postcss/postcss-loader#77]
I'm throwing in the towel. I've looked at how other projects are doing this, ran tutorials, even followed the readme and I'm still stuck. I'm not receiving any errors. In fact, everything appears fine except that I'm not seeing vendor prefixes. Because I'm not receiving any errors, I'm not sure what I'm doing wrong. 

Here's my setup

**webpack.config**
```js
var webpack      = require('webpack');
var path         = require('path');
var autoprefixer = require('autoprefixer')  ;
var precss       = require('precss');

var BUILD_DIR = path.resolve(__dirname, 'src/client/public');
var APP_DIR   = path.resolve(__dirname, 'src/client');
var ENTRY     = path.resolve(__dirname, 'src/client/index.js');

var config = {
  entry: ENTRY,
  output: {
    path: BUILD_DIR,
    filename: 'bundle.js'
  },
  module : {
    loaders : [
      {
        test : /\.js?/,
        include : APP_DIR,
        loader : 'babel'
      },
      {
        test: /\.css?$/,
        loaders: [
          'style-loader',
          'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          'postcss-loader'
        ]
      }
    ],
    postcss: function () {
      return [autoprefixer, precss];
    }
  }
};

module.exports = config;
```

CSS modules are loading just fine but autoprefixer and precss are not being applied.

I have a simple class
```css
.flex {
  display: flex;
}
```

Which should become...
```css
.flex {
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
}
```

I'm running the latest of the following packages:
**autoprefixer**: 6.3.6
**postcss-loader**: 0.9.1
**precss**:   1.4.0
**style-loader** 0.13.1
**css-loader**: 0.23.1

Any help or guidance would be appreciated!

**Comment by hankthewhale** [comment]
when I log `source` and `this`, I get the following,

**source**
```css
.common {
  composes: flex spaced v-centered from "../shared/flex-layout.css";
  composes: padded from "../shared/layout.css";
  composes: dark-bg light-text from "../shared/colors.css";
  composes: main-font-family from "../shared/typography.css";
}

.greeting {
  composes: massive-font from "../shared/typography.css";
}

.message {
  composes: large-font from "../shared/typography.css";
}
```

This all looks correct. All of these styles actually load and do the things they should... just no prefixed vendor names.

**this**
```js
{ data: undefined,
  inputValue: undefined,
  query: '',
  async: [Function: async],
  callback: [Function] }
.main-font-family {
  font-family: helvetica, arial, sans-serif;
}
```

**Comment by ai** [comment]
Could you add `a { display: flex }` in this file and show me the result?

**Comment by hankthewhale** [comment]
Sure thing. The output is:
```css
a {
  display: flex;
}
```

My previously logged **this** is still the same result as before.

**Comment by ai** [comment]
Do you use `browserslist` config?

**Comment by hankthewhale** [comment]
I do not. I wasn't sure if that was required. Many tutorials/demos I've seen do not pass in a browserlist config. That said, I did try it at some point and it still didn't work.

**Comment by ai** [comment]
Could you open `autoprefixer` sources in `node_modules` and put there `console.log` to test, that autoprefixer was executed? You need `lib/autoprefixer.js` and `module.exports` function.

**Comment by hankthewhale** [comment]
I put a console.log within `module.exports = postcss.plugin('autoprefixer', function() { });` and it fired so it appears that it is in fact calling it.

So it seems that postcss-loader is doing its job but autoprefixer is failing? Precss is also failing then.

**Comment by ai** [comment]
Could you debug `result.css` here? https://github.com/postcss/postcss-loader/blob/master/index.js#L67

**Comment by hankthewhale** [comment]
Here's the output of `result.css`

```css
.root {
  composes: flex spaced v-centered from "../shared/flex-layout.css";
  composes: padded from "../shared/layout.css";
  composes: dark-bg light-text from "../shared/colors.css";
  composes: main-font-family from "../shared/typography.css";
}

.greeting {
  composes: massive-font from "../shared/typography.css";
}

.message {
  composes: large-font from "../shared/typography.css";
}


a {
  display: flex;
}

.flex {
  display: flex;
}

.spaced {
  justify-content: space-between;
}

.v-centered {
  align-items: center;
}

.flex {
  display: flex;
}

.spaced {
  justify-content: space-between;
}

.v-centered {
  align-items: center;
}

.padded {
  padding: 1rem;
}

.padded-major {
  padding: 5rem;
}

.padded {
  padding: 1rem;
}

.padded-major {
  padding: 5rem;
}

.dark-bg {
  background: #212121;
}

.light-text {
  color: #efefef;
}

.dark-bg {
  background: #212121;
}

.light-text {
  color: #efefef;
}

.main-font-family {
  font-family: helvetica, arial, sans-serif;
}

.large-font {
  font-size: 2rem;
}

.massive-font {
  font-size: 7rem;
}

.main-font-family {
  font-family: helvetica, arial, sans-serif;
}

.large-font {
  font-size: 2rem;
}

.massive-font {
  font-size: 7rem;
}
```

**Comment by ai** [comment]
OK. So we sure, that its happen in Autoprefixer :-/

**Comment by hankthewhale** [comment]
Forgive me but just for clarification, are you saying that we're sure that it's a problem with autoprefixer?

**Comment by ai** [comment]
Could you write in CSS:

```
a {
  -webkit-border-radius: 5px;
  border-radius: 5px;
}
```

And show output?

**Comment by hankthewhale** [comment]
The output from `result.css`

```css
a {
  -webkit-border-radius: 5px;
  border-radius: 5px;
}
```
